### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-uxr5h#4]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by hayohtee** [comment]
Added default placeholder image for product catalog
![Screenshot_2022-09-21-17-31-06_1366x768](https://user-images.githubusercontent.com/94446638/191560826-768a0ef7-c7ae-4f08-b973-4f6aa2f837b7.png)
